services:

  postgres:
    image: postgres:16
    container_name: meeting-room-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meeting_room

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: meeting-room-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: