"""seed data

Revision ID: 8c79e3bee4f4
Revises: b924987cc39d
Create Date: 2026-09-29 10:52:03.573704

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8c79e3bee4f4"
down_revision: str | Sequence[str] | None = "b924987cc39d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
