"""create room and equipment tables

Revision ID: c6ea54c28172
Revises: 3cdf635158a5
Create Date: 2026-09-28 16:23:05.947444

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c6ea54c28172"
down_revision: str | Sequence[str] | None = "3cdf635158a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
